import { botonSiguientePagina } from "./BotonSiguiente.js";
import { botonAnteriorPagina } from "./BotonAnterior.js";
import { seleccionarPokemon } from "./SelecionoUnPokemon.js";
import { irAPagina } from "./IrAPagina.js";
import { botonVolver } from "./BotonVolver.js";
import { contendenorPokemones } from "../Cambio de pagina/Logica de paginacion/CreoPokedex.js";
document.querySelector("#botonSiguiente").onclick = botonSiguientePagina;
document.querySelector("#botonAnterior").onclick = botonAnteriorPagina;
contendenorPokemones.onclick = seleccionarPokemon;
document.querySelector("#irAPagina").onclick = irAPagina;
document.querySelector("#botonVolver").onclick = botonVolver;
